apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: vendor-empathy
spec:
  title: Vendor Empathy
  icon: https://avatars.githubusercontent.com/u/67430892?v=4
  statusInformers:
    - deployment/example-nginx
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
